### ISSUE TITLE
from common.threading import threads

### ISSUE THREAD

**Issue by yodatron** [anouarbensaad/vulnx#16]
I used the install instructions from Kitploit and when I tried to run I was informed there was no module named common, so I used pip to install common. I reran vulnx and was then informed that there was no module named common.threading. I looked on PyPl and could not find a specific 'common.threading' project, so I tried to install threads, no version found to satisfy requirements. While searching for projects under 'common.threading' on PyPl I found several projects listed. Which one is the one needed to get past this error? I will give that I am probably making a newb mistake, am willing to take this as a 'learning moment'!!

**Comment by anouarbensaad** [comment]
[click here to show common.threading](https://github.com/anouarbensaad/vulnx/blob/master/common/threading.py)
common is a local directory from **vulnx**.

**Comment by yodatron** [comment]
My real sticking point right now is getting past the threads module issue. Thanks though for clearing up the common issue. How do I import threads into this to clear up the problem?

**Comment by anouarbensaad** [comment]
Thank you i fix this issue, 
Now , Reclonning,
- `git clone https://github.com/anouarbensaad/vulnx`
- `cd vulnx`
- `chmod +x install.sh`
- `./install.sh`
check it now.

**Comment by yodatron** [comment]
ok...thanks....glad I could help...(?!)

**Comment by anouarbensaad** [comment]
Sure :100:
