### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dzhenway** [anouarbensaad/vulnx#22]
./vulnx.py -u "https://evil.com"
  File "./vulnx.py", line 468
    return print ('%s [+] Prestashop Version : %s %s' %(G,version,W))
               ^
SyntaxError: invalid syntax

**Comment by anouarbensaad** [comment]
**vulnx** work with python3

***


[CLICK HERE](https://github.com/anouarbensaad/vulnx/wiki/Compatibility-&-Dependencies) to show **Compatibility & Dependencies**

***

[INSTALL VULNX](https://github.com/anouarbensaad/vulnx#install-vulnx-on-ubuntu).and Run : 
`vulnx.py -u https://evil.com` 

or

- install python3
- install packages with pip install -r ./pip/requirements.txt
- run `python3 vulnx.py -u https://evil.com`

**Comment by dzhenway** [comment]
:~/Tools/vulnx$ pip install bs4
Collecting bs4
Collecting beautifulsoup4 (from bs4)
  Using cached https://files.pythonhosted.org/packages/8b/0e/048a2f88bc4be5e3697df9dc1f7b9d5c9c75be62676feeeb91d2e896c5ea/beautifulsoup4-4.7.1-py2-none-any.whl
Collecting soupsieve>=1.2 (from beautifulsoup4->bs4)
  Using cached https://files.pythonhosted.org/packages/b9/a5/7ea40d0f8676bde6e464a6435a48bc5db09b1a8f4f06d41dd997b8f3c616/soupsieve-1.9.1-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version < "3" (from soupsieve>=1.2->beautifulsoup4->bs4)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Installing collected packages: backports.functools-lru-cache, soupsieve, beautifulsoup4, bs4
Successfully installed backports.functools-lru-cache-1.5 beautifulsoup4-4.7.1 bs4-0.0.1 soupsieve-1.9.1
wayc0de@DESKTOP-76723ET:~/Tools/vulnx$ python3 vulnx.py -u  https://blog.jamtangan.com

:~/Tools/vulnx$ python3 vulnx.py -u  https://evil.com

Traceback (most recent call last):
  File "vulnx.py", line 25, in <module>
    from common.dnsdumperapi import dnsdumper , domain_info
  File "/home/wayc0de/Tools/vulnx/common/dnsdumperapi.py", line 6, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by dzhenway** [comment]
done installed on requirements.txt
but when tried running still got error

python3 vulnx.py -u  https://evil.com

Traceback (most recent call last):
  File "vulnx.py", line 25, in <module>
    from common.dnsdumperapi import dnsdumper , domain_info
  File "/home/wayc0de/Tools/vulnx/common/dnsdumperapi.py", line 6, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by dzhenway** [comment]
~ pip install bs4
Collecting bs4
Collecting beautifulsoup4 (from bs4)
  Using cached https://files.pythonhosted.org/packages/8b/0e/048a2f88bc4be5e3697df9dc1f7b9d5c9c75be62676feeeb91d2e896c5ea/beautifulsoup4-4.7.1-py2-none-any.whl
Collecting soupsieve>=1.2 (from beautifulsoup4->bs4)
  Using cached https://files.pythonhosted.org/packages/b9/a5/7ea40d0f8676bde6e464a6435a48bc5db09b1a8f4f06d41dd997b8f3c616/soupsieve-1.9.1-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version < "3" (from soupsieve>=1.2->beautifulsoup4->bs4)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Installing collected packages: backports.functools-lru-cache, soupsieve, beautifulsoup4, bs4
Successfully installed backports.functools-lru-cache-1.5 beautifulsoup4-4.7.1 bs4-0.0.1 soupsieve-1.9.1

**Comment by anouarbensaad** [comment]
- try to upgrade pip
- `pip install --upgrade pip`
or
- `install bs4 with pip3`

**Comment by dzhenway** [comment]
its worked!!!

thank mas
