### ISSUE TITLE
subdomains print in json format 

### ISSUE THREAD

**Issue by bretfeig** [anouarbensaad/vulnx#24]
Subdomains seem to dump on JSON formatting, not entirely sure why

~] Web Hosting Information
 [+] Domain Created on : 2000
 [+] CloudFlare IP : 194.176.124.50
 [+] Country : GB
 [+] Org : AS60610 Amito Ltd
-----------------------------------------------
 [~] Starting searching for Subdomains 

 [?] looking for subdomains
[{'domain': 'parispass.com', 'ip': '194.176.124.50', 'reverse_dns': '', 'as': 'AS60610', 'provider': 'Everest Data Centres Ltd', 'country': 'United Kingdom', 'header': 'ApacheHTTPS: Apache'}, {'domain': 'ppa.parispass.com', 'ip': '84.18.201.147', 'reverse_dns': '', 'as': 'AS29636', 'provider': 'catalyst2 Services Limited', 'country': 'United Kingdom', 'header': ''}, {'domain': 'm.parispass.com', 'ip': '84.18.201.51', 'reverse_dns': '', 'as': 'AS29636', 'provider': 'catalyst2 Services Limited', 'country': 'United Kingdom', 'header': ''}, {'domain': 'br.parispass.com', 'ip': '84.18.214.81', 'reverse_dns': '', 'as': 'AS29636', 'provider': 'catalyst2 Services Limited', 'country': 'United Kingdom', 'header': 'ApacheHTTPS: Apache'}, {'domain': 'www.parispass.com', 'ip': '194.176.124.50', 'reverse_dns': '', 'as': 'AS60610', 'provider': 'Everest Data Centres Ltd', 'country': 'United Kingdom', 'header': 'ApacheHTTPS: Apache'}, {'domain': 'mail.parispass.com', 'ip': '87.224.82.748', 'reverse_dns': '87-224-82-74.spitfireuk.net', 'as': 'AS16082', 'provider': 'Spitfire Network Services Limited', 'country': 'United Kingdom', 'header': 'Microsoft-IIS/10.0'}, {'domain': 'blog.parispass.com', 'ip': '84.18.201.150', 'reverse_dns': 'blog.lpg.dedicated.catalyst2.com', 'as': 'AS29636', 'provider': 'catalyst2 Services Limited', 'country': 'United Kingdom', 'header': 'ApacheHTTPS: Apache'}]

**Comment by anouarbensaad** [comment]
**check now if the text type fixed.**

![image](https://user-images.githubusercontent.com/23563528/58376110-6b919d00-7f5a-11e9-8581-f50f8ddfc09d.png)
