### ISSUE TITLE
Error in common/uri_converter.py 

### ISSUE THREAD

**Issue by expworm** [anouarbensaad/vulnx#25]
An error trying to check url's with the "minus" symbol in domain name like: something-likethis.com, cant provide the real domain name for security reasons.

Here is the traceback:
Traceback (most recent call last):
  File "/usr/share/vulnx/vulnx.py", line 514, in <module>
    'Host' : hostd(url),
  File "/usr/share/vulnx/common/uri_converter.py", line 6, in convert_uri
    return domain.group(3)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by anouarbensaad** [comment]
Can you verify if the fix works? and don't forget to install requirments.txt

***

**CMD :**
`pip install -r ./pip/requirements.txt`

**Comment by expworm** [comment]
Working like a charm! I run the ./update.sh then i started again vulnx with that domain and work great!
Thank's and Great work with vulnx.
