### ISSUE TITLE
Need Windows supported Version

### ISSUE THREAD

**Issue by rwelson** [anouarbensaad/vulnx#33]
Can we have windows supported version of Vulnx. Thanks for any help.

**Comment by mhaney3931** [comment]
i would love to see windows supported version too. hope so it will happen soon.

**Comment by anouarbensaad** [comment]
now vulnx **v1.5** will run correctly in windows & MacOS.

![Screenshot from 2019-05-31 02-59-24](https://user-images.githubusercontent.com/23563528/58676463-4d5be080-8350-11e9-8561-d375c92c1cd8.png)

**Comment by mhaney3931** [comment]
> now vulnx **v1.5** will run correctly in windows & MacOS.
> 
> ![Screenshot from 2019-05-31 02-59-24](https://user-images.githubusercontent.com/23563528/58676463-4d5be080-8350-11e9-8561-d375c92c1cd8.png)
First of all thanks a lot to make it supported for windows and mac.  
Any guide/help how to install on windows?

**Comment by anouarbensaad** [comment]
Steps :
- install python latest version
- clone vulnx repository and copy it to c:/
- open command prompt{CMD} and run : 
1 - `            cd c:/`
2 - `            python3 vulnx -u {URL} \or\ python3 vulnx -i {PATH FILE}`

**Comment by mhaney3931** [comment]
i did install python latest version. but it seems its not working. it stop working at checking for cms :  unknown. it did not start dns dumping and other process. i try with some sites and your given site too. so far no result .
