### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by rijinkcw** [anouarbensaad/vulnx#55]
perl@black:~/Desktop/SQL/vulnxv3$ ./install.sh
===== VULNX INSTALL =====
 [+] vulnx Will Be Installed In Your System
 [+] Installing Python ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Could not open requirements file: [Errno 2] No such file or directory: './pip/requirements.txt'
 [+] Checking directories...
 [+] Installing ...
 [+] Creating Symbolic Link ...
mkdir: cannot create directory ‘/usr/share/vulnx’: File exists
 [+] Tool Successfully Installed And Will Start In 5s!
 [+] You can execute tool by typing vulnx
Traceback (most recent call last):
  File "/usr/share/vulnx/vulnx.py", line 22, in <module>
    from common.threading import threads
ModuleNotFoundError: No module named 'common.threading'
perl@black:~/Desktop/SQL/vulnxv3$ vulnx
Traceback (most recent call last):
  File "/usr/share/vulnx/vulnx.py", line 22, in <module>
    from common.threading import threads
ModuleNotFoundError: No module named 'common.threading'
perl@black:~/Desktop/SQL/vulnxv3$

**Comment by anouarbensaad** [comment]
✅ Fixed..
