### ISSUE TITLE
can't run vulnx

### ISSUE THREAD

**Issue by mk2s1** [anouarbensaad/vulnx#57]
This is the error message I'm getting
Traceback (most recent call last):
  File "/usr/share/vulnx/vulnx.py", line 38, in <module>
    from modules.dnsLookup import dnsdumper,domain_info
  File "/usr/share/vulnx/modules/dnsLookup.py", line 6, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by larssorenson** [comment]
It appears you're missing the BeautifulSoup dependency. If you install the requirements.txt to your virtual environment you should be ok.

This can be done with the following:
`python -m pip install virtualenv` # only needed if you don't already have VirtualEnv installed
`python -m virtualenv vulnx_venv`
`source vulnx_venv/bin/activate`
`python -m pip install -r requirements.txt`

**Comment by pythonBlackHat** [comment]
guys plz dosent work in my windows 10

**Comment by anouarbensaad** [comment]
> guys plz dosent work in my windows 10

can you send me screenshot to know your error.

![58676463-4d5be080-8350-11e9-8561-d375c92c1cd8](https://user-images.githubusercontent.com/23563528/70356331-72d42480-1874-11ea-8337-c3e3b6ab3a07.png)
