### ISSUE TITLE
no log files 

### ISSUE THREAD

**Issue by wheelq** [anouarbensaad/vulnx#76]
**Describe the bug**
After running the scan, resulting in 0/0+ vulnerabilities, I can't see any log/result files being created.

**To Reproduce**
1. launch the scan
2. look for the log files

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser : N/A - Terminal
 - Version latest

**Comment by anouarbensaad** [comment]
![os_gethering](https://user-images.githubusercontent.com/23563528/79450816-5ba10280-7fdd-11ea-8c5e-f908d5baf418.png)
