### ISSUE TITLE
'NoneType' object

### ISSUE THREAD

**Issue by sertif85** [anouarbensaad/vulnx#79]
Traceback (most recent call last):
  File "/usr/share/vulnx/vulnx.py", line 719, in <module>
    detect_cms()
  File "/usr/share/vulnx/vulnx.py", line 533, in detect_cms
    wordpressMain(url,headers)
  File "/usr/share/vulnx/vulnx.py", line 259, in wordpressMain
    getOS(url, headers)
  File "/usr/share/vulnx/vulnx.py", line 609, in getOS
    print(' %s %sServer :%s %s' % (good, W, end, find.group(1)))
AttributeError: 'NoneType' object has no attribute 'group'

I caught a problem with the "Server" response header. This header did not exist in my case. Regular expression did not find a match and returned a None object.
This is my patch:
`find = regx.search(server_response)`
`if find is None:`
`print('"Server" header is not exist')`
`else:`
`print(' %s %sServer :%s %s' % (good, W, end, find.group(1)))`
`print(' %s %sOS :%s %s' % (good, W, end, find.group(2)))`

**Comment by anouarbensaad** [comment]
Thank you, i'm working to solve this issues.
```Python
    def os_server(self):
        response = requests.get(self.url, headers=self.headers).headers
        try:
            if response["server"]:
                regx = re.compile(r"(.+) \((.+)\)")
                data = regx.search(response["server"])
                print(' {} {}Server :{} {}' .format(good, W, end, data.group(1)))
                print(' {} {}OS :{} {}' .format(good, W, end, data.group(2)))
        except AttributeError as notfound:
            print(' {} Cannot Match the server headers : {}' .format(bad, str(notfound)))
```
