### ISSUE TITLE
A bug in docker/debian_stretch/Dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [anouarbensaad/vulnx#80]
https://github.com/anouarbensaad/vulnx/blob/9c04861ac7c46ee9544e443a35c78a13912e3fbf/docker/debian_stretch/Dockerfile#L50

Hi, we are developing a tool to detect bugs in dockerfile automatically. Our tool finds a bug above. Is it a bug? I think it should be `RUN apt-get -qq update &&\`. Thank you for your confirmation.

**Comment by anouarbensaad** [comment]
Oh it's cool,
thank you.
