### ISSUE TITLE
intup file option is broken

### ISSUE THREAD

**Issue by kusayuzayushko** [anouarbensaad/vulnx#83]
**Describe the bug**
-i / --input option doesn't work for me. Vuln just exit

**To Reproduce**
echo "http://google.com" > foo
vulnx -i foo -o bar

**Expected behavior**
expecting t to scan google

**Screenshots**
https://i.imgur.com/7EnvN0B.png

**Desktop (please complete the following information):**
 5.4.33-1-MANJARO
Blackarch

**Comment by anouarbensaad** [comment]
now you can run.
```BASH
vulnx -i [INPUT_FILE]
```
and works fine.
thank you for your request.
